In [1]:
import numpy as np 

In [6]:
W  =  np.array([[i for i in range(1,4)],
                [i for i in range(4,7)]])
X  =  np.array([[i for i in range(3)],
                [i for i in range(3,6)]])

In [7]:
W,X

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [4]:
W+X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [8]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [9]:
"""broading cast"""
w=np.array([1])
w+W

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
print(W)
print(X.T)
np.dot(W,X.T)

[[1 2 3]
 [4 5 6]]
[[0 3]
 [1 4]
 [2 5]]


array([[ 8, 26],
       [17, 62]])